ProjetoEntityFramework/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoEntityFramework.Models
{
    public class Categoria
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public bool PermiteEstoque { get; set; }
    }
}

ProjetoEntityFramework/Models/ErrorViewModel.cs
using System;

namespace ProjetoEntityFramework.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoEntityFramework/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoEntityFramework.Models
{
    public class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Categoria Categoria { get; set; }
        public int CategoriaId { get; set; }
        public bool Ativo { get; set; }
    }
}

ProjetoEntityFramework/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoEntityFramework.Models;

namespace ProjetoEntityFramework.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ApplicationContext _context;
        public CategoriaController(ApplicationContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var categoria = _context.Categoria.ToList();
            return View(categoria);
        }

        public IActionResult Editar(int id)
        {
            var categoria = _context.Categoria.First(c => c.Id == id);

            return View("Salvar", categoria);
        }


        public async Task<IActionResult> Excluir(int id)
        {
            var categoria = _context.Categoria.First(c => c.Id == id);
            _context.Categoria.Remove(categoria);
           await  _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Salvar()
        {
           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Salvar(Categoria categoria)
        {
            // se o Id for 0 é porque o produto é novo, pois o id é preenchido automatizamente peo banco, e não pelo usuário
            if (categoria.Id == 0)
            {
                _context.Categoria.Add(categoria);
            }
            //Casa o Id não seja igual a 0, é porque é uma categoria já existente, e o usuário está querendo alterar o valor
            else
            {
                var categoriaJaSalva = _context.Categoria.First(c => c.Id == categoria.Id);
                categoriaJaSalva.Nome = categoria.Nome;
                categoriaJaSalva.PermiteEstoque = categoria.PermiteEstoque;
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ProjetoEntityFramework/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoEntityFramework.Models;

namespace ProjetoEntityFramework.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoEntityFramework/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoEntityFramework.Models;

namespace ProjetoEntityFramework.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ApplicationContext _context;
        public ProdutoController(ApplicationContext context)
        {
            _context = context;
        }
       
        [HttpGet]
        public IActionResult Index()
        {
            // Como a tabela produto possui atributos ligado com categoria, é preciso dá um 'include(tabela desejada)'
            // Ou seja, toda a vez que for precisar listar um objeto e este objeto tiver relacionado a outro, tem que usar o include
            //var produtos = _context.Produto.Include(p => p.Categoria).ToList();

            var queryDeProduto = _context.Produto
               .Where(p => p.Ativo && p.Categoria.PermiteEstoque)
                 .OrderBy(p => p.Nome);

            

            if (!queryDeProduto.Any())
                return View(new List<Produto>());

            return View(queryDeProduto.ToList());

        }

        [HttpGet]
        public  IActionResult Editar(int id)
        {
            ViewBag.Categoria = _context.Categoria.ToList();
            var produto = _context.Produto.First(p => p.Id == id);
            return View("Salvar", produto);
        }

        public async Task<IActionResult> Excluir(int id)
        {
            var produto = _context.Produto.First(p => p.Id == id);
            _context.Produto.Remove(produto);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Salvar()
        {
            ViewBag.Categoria = _context.Categoria.ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Salvar(Produto produto)
        {
            _context.Produto.Add(produto);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ProjetoEntityFramework/Views/Categoria/Index.cshtml
@model  IEnumerable<ProjetoEntityFramework.Models.Categoria>
@{
    ViewData["Title"] = "Index";
}

<h2>Todas Categorias</h2>
<a href="/Categoria/Salvar" class="btn">Cadastrar Categoria</a>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.Nome</td>
                    <td>
                        <a href="/Categoria/Editar/@item.Id" class="btn">Editar</a>
                    </td>
                    <td>
                        <a href="/Categoria/Excluir/@item.Id" class="btn">Excluir</a>
                    </td>
                </tr>
                }
            </tbody>
        </table> 
    </div>
 </div>

ProjetoEntityFramework/Views/Categoria/Salvar.cshtml
@model  ProjetoEntityFramework.Models.Categoria
@{
    ViewData["Title"] = "Salvar";
}

<h2>Formulário de Categoria</h2>


<form class="form-horizontal" asp-action="Salvar" asp-controller="Categoria" method="post">

    <!--  O input abaixo foi declarado para obter o Id da categoria que deseja Editar  -->

    <input type="hidden" class="form-control" asp-for="Id" />

    <div class="form-group">

        <label class="col-md-1 control-label" for="Name">Nome</label>
        <div class="col-md-2">
            <input type="text" class="form-control" asp-for="Nome">
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-1 control-label" for="Name">Estoque</label>
        <div class="col-md-2">
            <input type="checkbox" asp-for="PermiteEstoque">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-2">
            <button class="btn btn-success">Salvar</button>
        </div>
    </div>


</form>

ProjetoEntityFramework/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ProjetoEntityFramework/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjetoEntityFramework/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ProjetoEntityFramework/Views/Produto/Index.cshtml
@model IEnumerable<ProjetoEntityFramework.Models.Produto>

<h2>Todos Produtos</h2>

<a href="/Produto/Salvar" class="btn">Novo Produto</a>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Nome</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nome </td>
                       
                        <td>
                            <a href="/Produto/Editar/@item.Id" class="btn">Editar</a>
                        </td>
                        <td>
                            <a href="/Produto/Excluir/@item.Id" class="btn">Deletar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ProjetoEntityFramework/Views/Produto/Salvar.cshtml
@model  ProjetoEntityFramework.Models.Produto

@{
    ViewData["Title"] = "Salvar";
}

<h2>Formulário de Produto</h2>

<form class="form-horizontal" asp-action="Salvar" asp-controller="Produto" method="post">

    <input type="hidden" class="form-control" asp-for="Id">
    <div class="form-group">
        <label class="col-md-1 control-label" for="Name">Nome:</label>
        <div class="col-md-2">
            <input type="text" class="form-control" asp-for="Nome">
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-1 control-label" for="Categoria">Categoria</label>
        <div class="col-md-2">
            <select class="form-control" asp-for="CategoriaId"
                    asp-items='@(new SelectList(@ViewBag.Categoria, "Id", "Nome"))'></select>
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-1 control-label" for="Ativo">Ativo</label>
        <div class="col-md-2">
            <input type="checkbox" asp-for="Ativo">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            <button class="btn btn-success">Salvar</button>
        </div>
    </div>

</form>

ProjetoEntityFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoEntityFramework</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ProjetoEntityFramework</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a></li>
                    <li><a asp-area="" asp-controller="Produto" asp-action="Index">Produto</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ProjetoEntityFramework</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>